/**
 * Card definitions for FoulPlay game
 * Cards are organized by sport and include severity levels.
 * All penalties are for the card holder only.
 */

export type Sport = "football" | "basketball";
export type Severity = "mild" | "moderate" | "severe";
export type CardType = "action" | "challenge" | "penalty";

/** hf = high-frequency (visual/broadcast/commercial); common = gameplay; rare = big moments */
export type Tier = "hf" | "common" | "rare";

export interface CardDefinition {
  sport: Sport;
  title: string;
  description: string;
  severity: Severity;
  type: CardType;
  points: number; // Points awarded for this card
  tier: Tier;
}

/**
 * Penalty text constants.
 * Keep these centralized so we can:
 * - quickly tune difficulty across the whole deck
 * - support non-drinking modes later (swap these strings)
 * - avoid inconsistent wording / typos
 */
export const PENALTIES = {
  DRINK: "Take a drink",
  TWO_DRINKS: "Take 2 drinks",
  THREE_DRINKS: "Take 3 drinks",
  SHOT: "Take a shot",
  SHOTGUN: "Shotgun a beer",
  FINISH: "Finish your drink",
  FINISH_HALF: "Finish your drink + 1/2 another",
} as const;

// -------------------
// FOOTBALL (Revamped ~55 + High-Frequency Add-ons)
// -------------------
export const FOOTBALL_CARDS: CardDefinition[] = [
  // Mild (Common Gameplay Events)
  {
    sport: "football",
    title: "Incomplete Pass",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Complete Pass",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Run Play",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "First Down",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Third Down Conversion",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 2,
    tier: "common",
  },
  {
    sport: "football",
    title: "Three-and-Out",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  {
    sport: "football",
    title: "QB Scramble",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "QB Slides",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "QB Throws It Away",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  {
    sport: "football",
    title: "Punt",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Touchback",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Fair Catch",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  // Mild (Common Penalties - broad, recognizable)
  {
    sport: "football",
    title: "False Start",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Offside",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Holding (Any Team)",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Delay of Game",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Pass Interference",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 3,
    tier: "common",
  },
  {
    sport: "football",
    title: "Personal Foul",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 4,
    tier: "common",
  },

  // Moderate (Pressure / Momentum)
  {
    sport: "football",
    title: "Sack",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 3,
    tier: "common",
  },
  {
    sport: "football",
    title: "Big Run (20+ yards)",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 3,
    tier: "common",
  },
  {
    sport: "football",
    title: "Big Pass (25+ yards)",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 3,
    tier: "common",
  },
  {
    sport: "football",
    title: "Red Zone Trip",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 3,
    tier: "common",
  },
  {
    sport: "football",
    title: "Goal Line Stand",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 4,
    tier: "common",
  },

  {
    sport: "football",
    title: "Field Goal Made",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 3,
    tier: "common",
  },
  {
    sport: "football",
    title: "Missed Field Goal",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 2,
    tier: "common",
  },
  {
    sport: "football",
    title: "Extra Point Missed",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 2,
    tier: "common",
  },
  {
    sport: "football",
    title: "Two-Point Attempt",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 4,
    tier: "common",
  },

  // Turnovers (Big moments)
  {
    sport: "football",
    title: "Fumble",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 4,
    tier: "common",
  },
  {
    sport: "football",
    title: "Turnover (Any)",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 5,
    tier: "common",
  },
  {
    sport: "football",
    title: "Interception",
    description: PENALTIES.SHOT,
    severity: "moderate",
    type: "penalty",
    points: 5,
    tier: "common",
  },

  // Game Flow / Broadcast Staples
  {
    sport: "football",
    title: "Timeout Called",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Coach Challenge",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Replay Review",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Two-Minute Warning",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 2,
    tier: "common",
  },
  {
    sport: "football",
    title: "Injury Timeout",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  // Severe (Rare / Game-Changing) — card-holder only
  {
    sport: "football",
    title: "Touchdown",
    description: PENALTIES.FINISH,
    severity: "severe",
    type: "penalty",
    points: 7,
    tier: "rare",
  },
  {
    sport: "football",
    title: "Pick-Six",
    description: PENALTIES.SHOTGUN,
    severity: "severe",
    type: "penalty",
    points: 8,
    tier: "rare",
  },
  {
    sport: "football",
    title: "Kickoff Return TD",
    description: PENALTIES.SHOTGUN,
    severity: "severe",
    type: "penalty",
    points: 8,
    tier: "rare",
  },
  {
    sport: "football",
    title: "Fumble Return TD",
    description: PENALTIES.SHOTGUN,
    severity: "severe",
    type: "penalty",
    points: 8,
    tier: "rare",
  },
  {
    sport: "football",
    title: "Safety",
    description: PENALTIES.FINISH_HALF,
    severity: "severe",
    type: "penalty",
    points: 8,
    tier: "rare",
  },
  {
    sport: "football",
    title: "Overtime",
    description: PENALTIES.FINISH,
    severity: "severe",
    type: "penalty",
    points: 7,
    tier: "rare",
  },
  {
    sport: "football",
    title: "Game-Winning Touchdown",
    description: PENALTIES.FINISH_HALF,
    severity: "severe",
    type: "penalty",
    points: 9,
    tier: "rare",
  },
  {
    sport: "football",
    title: "Game-Winning Field Goal",
    description: PENALTIES.FINISH_HALF,
    severity: "severe",
    type: "penalty",
    points: 9,
    tier: "rare",
  },

  // Fun Broadcast Moments
  {
    sport: "football",
    title: "Announcer Says 'Rookie'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Announcer Says 'Veteran Presence'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Announcer Mentions 'Momentum'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Coach Seen Yelling on Sideline",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Crowd Goes Wild on a Replay",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },

  // Commercial Cards
  {
    sport: "football",
    title: "Beer Commercial",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Car Commercial",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Fast Food Commercial",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Sports Betting Commercial",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Insurance Commercial",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },

  {
    sport: "football",
    title: "Animal in a Commercial",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Celebrity in a Commercial",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Same Commercial Plays Twice",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 3,
    tier: "hf",
  },

  // Optional Rarities
  {
    sport: "football",
    title: "Hail Mary Attempt",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 4,
    tier: "common",
  },
  {
    sport: "football",
    title: "Successful Hail Mary",
    description: PENALTIES.SHOTGUN,
    severity: "severe",
    type: "penalty",
    points: 9,
    tier: "rare",
  },

  // -------------------
  // FOOTBALL: High-Frequency Add-ons (~50)
  // -------------------

  // Visual / Uniform / Gear (super frequent)
  {
    sport: "football",
    title: "Player Wearing Red Shoes",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Player Wearing White Shoes",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Player Wearing Bright/Neon Shoes",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Player Wearing a Visor",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Player With Tinted Visor",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Player Wearing Arm Sleeves",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Player Wearing Gloves",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Player Tapes Fingers",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Player With a Towel Hanging",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Player With a Mouthguard Dangling",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  // Jersey / Team Color (always true, keeps flow)
  {
    sport: "football",
    title: "Team Wearing White Jerseys",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Team Wearing Dark Jerseys",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Team Has Red in Jerseys",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Team Has Blue in Jerseys",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Team Has Black in Jerseys",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Team Has Green in Jerseys",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  // Ref / Flags / Chains (constant appearances)
  {
    sport: "football",
    title: "Ref Announces a Call",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Ref Uses the Mic",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Yellow Flag Shown on Screen",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Camera Shows the Chain Crew",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Camera Shows the First-Down Marker/Line",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },

  // Broadcast / Graphics (every drive)
  {
    sport: "football",
    title: "Score Bug Shows a Stat Graphic",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Graphic Shows '3rd Down'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Graphic Shows Timeouts Remaining",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Graphic Shows 'Red Zone'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Split-Screen Shows Coach + Field",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  // Sideline / Crowd Shots (very frequent)
  {
    sport: "football",
    title: "Camera Shows the Cheerleaders",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Camera Shows a Kid in Team Gear",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Camera Shows a Fan in Face Paint",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Camera Shows a Superfan Costume",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Camera Shows a Celebrity in the Stands",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },

  // Announcer Phrases (super common)
  {
    sport: "football",
    title: "Announcer Says 'Great Protection'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Announcer Says 'Pocket Presence'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Announcer Says 'Play Action'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Announcer Says 'Miscommunication'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Announcer Says 'Great Route'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Announcer Says 'Ball Security'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },

  // Common Micro-Events (still game-related, but frequent)
  {
    sport: "football",
    title: "Receiver Steps Out of Bounds",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Short Gain (1–3 yards)",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "No Gain on a Play",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Tackle Made in the Open Field",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "QB Claps/Signals for the Snap",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  // Commercial / Break Micro-Triggers (keeps flow even during breaks)
  {
    sport: "football",
    title: "Promo for Another Show",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Network Mentions the App/Streaming",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Commercial Shows Food Close-Up",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Commercial Has a Catchy Jingle",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },

  // “Always Works” Wildcards (low points, keep it moving)
  {
    sport: "football",
    title: "Camera Shows a Player Smiling",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Camera Shows a Player Arguing",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "football",
    title: "Coach Puts Hands on Hips",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "football",
    title: "Camera Shows a Player on the Bench",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
];

// -------------------
// BASKETBALL (Revamped ~50 + High-Frequency Add-ons)
// -------------------
export const BASKETBALL_CARDS: CardDefinition[] = [
  // Mild (Common Events)
  {
    sport: "basketball",
    title: "Made 3-Pointer",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Missed 3-Pointer",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Made Free Throw",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Missed Free Throw",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Made Layup",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Missed Layup",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  {
    sport: "basketball",
    title: "Defensive Rebound",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Offensive Rebound",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  {
    sport: "basketball",
    title: "Turnover",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Steal",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Block",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  {
    sport: "basketball",
    title: "Personal Foul",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Shooting Foul",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  {
    sport: "basketball",
    title: "Timeout",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Replay Review",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  {
    sport: "basketball",
    title: "Airball",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 2,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Traveling",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 2,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Double Dribble",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 2,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Shot Clock Violation",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 2,
    tier: "common",
  },

  {
    sport: "basketball",
    title: "Out of Bounds Turnover",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Fast Break Score",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  // Moderate (Hype Events)
  {
    sport: "basketball",
    title: "Dunk",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 3,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Alley-Oop Dunk",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 4,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "And-One",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 3,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "4-Point Play",
    description: PENALTIES.THREE_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 5,
    tier: "common",
  },

  {
    sport: "basketball",
    title: "Technical Foul",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 4,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Coach Challenge",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 3,
    tier: "common",
  },

  {
    sport: "basketball",
    title: "Player Fouls Out",
    description: PENALTIES.THREE_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 5,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "10–0 Run",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 4,
    tier: "common",
  },

  // Severe (Rare / Big Moments) — card-holder only
  {
    sport: "basketball",
    title: "Buzzer Beater (End of Quarter)",
    description: PENALTIES.SHOT,
    severity: "severe",
    type: "penalty",
    points: 6,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Game-Winning Shot",
    description: PENALTIES.SHOTGUN,
    severity: "severe",
    type: "penalty",
    points: 8,
    tier: "rare",
  },
  {
    sport: "basketball",
    title: "Half-Court Shot Made",
    description: PENALTIES.FINISH,
    severity: "severe",
    type: "penalty",
    points: 8,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Overtime",
    description: PENALTIES.FINISH,
    severity: "severe",
    type: "penalty",
    points: 7,
    tier: "rare",
  },
  {
    sport: "basketball",
    title: "Flagrant Foul",
    description: PENALTIES.FINISH_HALF,
    severity: "severe",
    type: "penalty",
    points: 7,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Player Ejected",
    description: PENALTIES.SHOTGUN,
    severity: "severe",
    type: "penalty",
    points: 8,
    tier: "common",
  },

  // Fun / Broadcast Moments
  {
    sport: "basketball",
    title: "Announcer Says 'Heat Check'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Celebrity Shown Courtside",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Coach Looks Furious",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Player Complains to Ref",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Bench Celebration",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Slow Motion Replay",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  // Commercial Cards
  {
    sport: "basketball",
    title: "Beer Commercial",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Car Commercial",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Fast Food Commercial",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Sports Betting Commercial",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Insurance Commercial",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },

  {
    sport: "basketball",
    title: "Animal in a Commercial",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Celebrity in a Commercial",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Same Commercial Plays Twice",
    description: PENALTIES.TWO_DRINKS,
    severity: "moderate",
    type: "penalty",
    points: 3,
    tier: "hf",
  },

  // -------------------
  // BASKETBALL: High-Frequency Add-ons (~50)
  // -------------------

  // Visual / Uniform / Gear (very frequent)
  {
    sport: "basketball",
    title: "Player Wearing Red Shoes",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Player Wearing White Shoes",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Player Wearing Bright/Neon Shoes",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Player Wearing a Headband",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Player Wearing an Arm Sleeve",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Player Wearing Two Arm Sleeves",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Player Wearing a Leg Sleeve",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Player Wearing a Face Mask",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Player Wearing a Mouthguard",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Player With Taped Fingers",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  // Team / Jersey Color (always present)
  {
    sport: "basketball",
    title: "Team Wearing White Jerseys",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Team Wearing Dark Jerseys",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Team Has Red in Jerseys",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Team Has Blue in Jerseys",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Team Has Black in Jerseys",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  // Broadcast / Graphics (constant)
  {
    sport: "basketball",
    title: "Graphic Shows Player Points",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Graphic Shows Shooting %",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Graphic Shows Team Fouls",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Graphic Shows Bonus/Free Throws",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Split-Screen Shows Coach + Court",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  // Crowd / Sideline Shots
  {
    sport: "basketball",
    title: "Camera Shows Courtside Fans Reacting",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Camera Shows a Kid in Team Gear",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Camera Shows a Fan in Face Paint",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Camera Shows Mascot",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Camera Shows Dance Team",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },

  // Ref Moments (frequent)
  {
    sport: "basketball",
    title: "Ref Blows the Whistle",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Ref Signals a Foul",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Ref Signals 'Three'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Ref Signals 'Travel'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  // Announcer Phrases (high hit-rate)
  {
    sport: "basketball",
    title: "Announcer Says 'Good Look'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Announcer Says 'Great Defense'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Announcer Says 'No Call'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Announcer Says 'In Transition'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Announcer Says 'Paint Points'",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },

  // Common Micro-Events (very frequent)
  {
    sport: "basketball",
    title: "Player Claps After a Play",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Player Points to a Teammate",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Player Flexes After a Bucket",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Bench Stands Up",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Coach Calls a Play (Hand Signals)",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },

  // Break / Arena / In-Game Entertainment
  {
    sport: "basketball",
    title: "Arena Plays a Loud Sound Effect",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "common",
  },
  {
    sport: "basketball",
    title: "Crowd 'Defense!' Chant",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "T-Shirt Cannon / Giveaway",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Kiss Cam / Fan Cam",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },

  // “Always Works” Wildcards
  {
    sport: "basketball",
    title: "Camera Shows Player Smiling",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Camera Shows Player Arguing",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Camera Shows Coach Hands on Hips",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
  {
    sport: "basketball",
    title: "Camera Shows Player on the Bench",
    description: PENALTIES.DRINK,
    severity: "mild",
    type: "penalty",
    points: 1,
    tier: "hf",
  },
];

export function getCardsForSport(sport: Sport): CardDefinition[] {
  switch (sport) {
    case "football":
      return FOOTBALL_CARDS;
    case "basketball":
      return BASKETBALL_CARDS;
    default:
      return [];
  }
}
