/**
 * Card definitions for FoulPlay game
 * Cards are organized by sport and include severity levels
 */

export type Sport = "football" | "basketball";
export type Severity = "mild" | "moderate" | "severe";
export type CardType = "action" | "challenge" | "penalty";

export interface CardDefinition {
  sport: Sport;
  title: string;
  description: string;
  severity: Severity;
  type: CardType;
  points: number; // Points awarded for this card
}

export const FOOTBALL_CARDS: CardDefinition[] = [
  // Mild penalties (1-3 points) - Most common
  {
    sport: "football",
    title: "Incomplete Pass",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "False Start Penalty",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Automatic First Down",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Announcer says 'Rookie'",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "QB throws the ball away",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Offside",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Delay of Game",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Holding Penalty",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Pass Interference",
    description: "Take 2 drinks",
    severity: "moderate",
    type: "penalty",
    points: 3,
  },
  {
    sport: "football",
    title: "Illegal Formation",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Encroachment",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Neutral Zone Infraction",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Illegal Motion",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Illegal Shift",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Illegal Substitution",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Too Many Men on Field",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Intentional Grounding",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Ineligible Receiver",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Illegal Block",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Clipping",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Face Mask",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Roughing the Passer",
    description: "Take 2 drinks",
    severity: "moderate",
    type: "penalty",
    points: 3,
  },
  {
    sport: "football",
    title: "Roughing the Kicker",
    description: "Take 2 drinks",
    severity: "moderate",
    type: "penalty",
    points: 3,
  },
  {
    sport: "football",
    title: "Unsportsmanlike Conduct",
    description: "Take 2 drinks",
    severity: "moderate",
    type: "penalty",
    points: 4,
  },
  {
    sport: "football",
    title: "Taunting",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Excessive Celebration",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Missed Field Goal",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Missed Extra Point",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Punt",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Fair Catch",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Touchback",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Three and Out",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Sack",
    description: "Take 2 drinks",
    severity: "moderate",
    type: "penalty",
    points: 3,
  },
  {
    sport: "football",
    title: "Fumble (Recovered)",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Timeout Called",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Challenge Flag",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Two-Minute Warning",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Commercial Break",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Injury Timeout",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Fourth Down",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "football",
    title: "Red Zone",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "football",
    title: "Goal Line Stand",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "football",
    title: "Hail Mary Attempt",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "football",
    title: "Onside Kick",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "football",
    title: "Fake Punt",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "football",
    title: "Fake Field Goal",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "football",
    title: "Trick Play",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "football",
    title: "Two-Point Conversion Attempt",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 3,
  },
  {
    sport: "football",
    title: "Overtime",
    description: "Take 2 drinks",
    severity: "moderate",
    type: "penalty",
    points: 4,
  },

  // Moderate penalties (4-6 points) - Less common
  {
    sport: "football",
    title: "Interception",
    description: "Take a shot",
    severity: "moderate",
    type: "penalty",
    points: 4,
  },
  {
    sport: "football",
    title: "Turnover",
    description: "Take 2 drinks",
    severity: "moderate",
    type: "penalty",
    points: 5,
  },
  {
    sport: "football",
    title: "Fumble Lost",
    description: "Take 2 drinks",
    severity: "moderate",
    type: "penalty",
    points: 5,
  },
  {
    sport: "football",
    title: "Pick-Six",
    description: "Shotgun a beer",
    severity: "severe",
    type: "penalty",
    points: 7,
  },
  {
    sport: "football",
    title: "Fumble Return TD",
    description: "Shotgun a beer",
    severity: "severe",
    type: "penalty",
    points: 7,
  },
  {
    sport: "football",
    title: "Blocked Punt",
    description: "Shotgun a beer",
    severity: "severe",
    type: "penalty",
    points: 7,
  },
  {
    sport: "football",
    title: "Blocked Field Goal",
    description: "Shotgun a beer",
    severity: "severe",
    type: "penalty",
    points: 7,
  },
  {
    sport: "football",
    title: "Personal Foul",
    description: "Take 2 drinks",
    severity: "moderate",
    type: "penalty",
    points: 5,
  },
  {
    sport: "football",
    title: "Unnecessary Roughness",
    description: "Take 2 drinks",
    severity: "moderate",
    type: "penalty",
    points: 5,
  },
  {
    sport: "football",
    title: "Ejection",
    description: "Shotgun a beer",
    severity: "severe",
    type: "penalty",
    points: 8,
  },
  {
    sport: "football",
    title: "Disqualification",
    description: "Shotgun a beer",
    severity: "severe",
    type: "penalty",
    points: 8,
  },

  // Severe penalties (7-10 points) - Rare
  {
    sport: "football",
    title: "Safety",
    description: "Shotgun a beer",
    severity: "severe",
    type: "penalty",
    points: 8,
  },
  {
    sport: "football",
    title: "Game-Winning Touchdown",
    description: "Everyone shotguns",
    severity: "severe",
    type: "penalty",
    points: 8,
  },
  {
    sport: "football",
    title: "Hail Mary Completion",
    description: "Everyone shotguns",
    severity: "severe",
    type: "penalty",
    points: 9,
  },
  {
    sport: "football",
    title: "Game-Winning Field Goal",
    description: "Everyone finishes their drink",
    severity: "severe",
    type: "penalty",
    points: 10,
  },
  {
    sport: "football",
    title: "Offensive Holding",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Defensive Holding",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Illegal Contact",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Illegal Use of Hands",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "QB Sacked",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "QB Hit",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "QB Pressure",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "QB Scramble",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "QB Slide",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "QB Spike",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "QB Kneel",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "QB Sneak",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "RB Rush",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "RB Fumble",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "RB Stuffed",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "RB Loss",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "WR Drop",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "WR Out of Bounds",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "WR Push Off",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "TE Drop",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "TE Block",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "OL Holding",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "OL False Start",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "DL Sack",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "DL Tackle for Loss",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "DL QB Hit",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "DL QB Pressure",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "LB Tackle",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "LB Blitz",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "LB Coverage",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "DB Pass Breakup",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "DB Coverage",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "DB Tackle",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "K Missed FG",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "K Missed XP",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "football",
    title: "Game-Ending Play",
    description: "Everyone finishes their drink",
    severity: "severe",
    type: "penalty",
    points: 10,
  },
];

export const BASKETBALL_CARDS: CardDefinition[] = [
  // Mild penalties (1-3 points) - Most common
  {
    sport: "basketball",
    title: "Missed 3-Pointer",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Pick and Roll",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Defensive Rebound",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Offensive Foul",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Free Throw",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Traveling",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Double Dribble",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Shot Clock Violation",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Personal Foul",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Layup",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Airball",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Turnover",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Jump Shot",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Out of Bounds",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Backcourt Violation",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "3-Second Violation",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "5-Second Violation",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "8-Second Violation",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Offensive Rebound",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Hook Shot",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Fadeaway",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Charging Foul",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Blocking Foul",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Shooting Foul",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Loose Ball Foul",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Illegal Screen",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Goaltending",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Basket Interference",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Bank Shot",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "basketball",
    title: "Missed Fadeaway Jumper",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "basketball",
    title: "Missed Step-Back",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "basketball",
    title: "Missed Pull-Up Jumper",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "basketball",
    title: "Missed Mid-Range",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "basketball",
    title: "Missed Corner 3",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "basketball",
    title: "Missed Fast Break",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "basketball",
    title: "Missed Open Shot",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "basketball",
    title: "Missed Contested Shot",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 2,
  },
  {
    sport: "basketball",
    title: "Missed And-One",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 3,
  },
  {
    sport: "basketball",
    title: "Missed Game-Tying Shot",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 3,
  },

  // Moderate penalties (4-6 points) - Less common
  {
    sport: "basketball",
    title: "Technical Foul",
    description: "Specific drink/shot instruction",
    severity: "moderate",
    type: "penalty",
    points: 4,
  },
  {
    sport: "basketball",
    title: "Player Dunk",
    description: "Specific drink instruction",
    severity: "moderate",
    type: "penalty",
    points: 4,
  },
  {
    sport: "basketball",
    title: "Flagrant Foul",
    description: "Shotgun a beer",
    severity: "severe",
    type: "penalty",
    points: 7,
  },
  {
    sport: "basketball",
    title: "Ejection",
    description: "Shotgun a beer",
    severity: "severe",
    type: "penalty",
    points: 8,
  },
  {
    sport: "basketball",
    title: "Missed Game-Winning Shot",
    description: "Take 2 drinks",
    severity: "moderate",
    type: "penalty",
    points: 5,
  },
  {
    sport: "basketball",
    title: "Fouled Out",
    description: "Shotgun a beer",
    severity: "severe",
    type: "penalty",
    points: 7,
  },
  {
    sport: "basketball",
    title: "Flagrant Foul 2",
    description: "Shotgun a beer",
    severity: "severe",
    type: "penalty",
    points: 9,
  },
  {
    sport: "basketball",
    title: "Unsportsmanlike Conduct",
    description: "Shotgun a beer",
    severity: "severe",
    type: "penalty",
    points: 7,
  },

  // Severe penalties (7-10 points) - Rare
  {
    sport: "basketball",
    title: "Buzzer Beater",
    description: "Shotgun a beer",
    severity: "severe",
    type: "penalty",
    points: 7,
  },
  {
    sport: "basketball",
    title: "Game-Winning Buzzer Beater",
    description: "Everyone shotguns",
    severity: "severe",
    type: "penalty",
    points: 9,
  },
  {
    sport: "basketball",
    title: "Half-Court Shot Made",
    description: "Everyone else shotguns",
    severity: "severe",
    type: "penalty",
    points: 9,
  },
  {
    sport: "basketball",
    title: "Full-Court Shot Made",
    description: "Everyone else finishes their drink",
    severity: "severe",
    type: "penalty",
    points: 10,
  },
  // Additional basketball cards to reach 100
  {
    sport: "basketball",
    title: "Missed Fadeaway Jumper",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Turnaround Jumper",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Running Jumper",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Pull-Up Jumper",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Step-Back 3",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Corner 3",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Wing 3",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Top of Key 3",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Baseline Jumper",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Elbow Jumper",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Short Corner",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Post-Up",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Hook Shot",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Finger Roll",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Floater",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Runner",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Tear Drop",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Euro Step",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Reverse Layup",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Up and Under",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Drop Step",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Spin Move",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Crossover",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Behind the Back",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Between the Legs",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Behind the Back Pass",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed No-Look Pass",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Alley-Oop",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Putback",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Tip-In",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Follow-Up",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Second Chance",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Fast Break",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Transition",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Breakaway",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Open Look",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Wide Open",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Contested Layup",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Contested 3",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Contested Mid-Range",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Off-Balance",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Fadeaway 3",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Step-Back 3",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Pull-Up 3",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Catch and Shoot",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Spot-Up",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Off the Dribble",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Off Screen",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
  {
    sport: "basketball",
    title: "Missed Handoff",
    description: "Take a drink",
    severity: "mild",
    type: "penalty",
    points: 1,
  },
];

export function getCardsForSport(sport: Sport): CardDefinition[] {
  switch (sport) {
    case "football":
      return FOOTBALL_CARDS;
    case "basketball":
      return BASKETBALL_CARDS;
    default:
      return [];
  }
}
